/* ═══════════════════════════════════════════════════════════
   PILIERS SECTORIELS — contenu rédigé sur-mesure par (secteur × zone).
   Objectif : autorité thématique + unicité forte (aucune substitution
   de variable creuse). Chaque entrée CONTENT[secteur][zone] est un texte
   propre au métier ET au territoire.

   Consommé par : zones/generate-sectors.mjs
   → /{zone}/secteurs/{secteur}.html + /{zone}/secteurs/index.html

   Ajouter une zone à un secteur = ajouter CONTENT[secteur][zoneSlug].
   Le générateur ne produit que les couples réellement rédigés.
   ═══════════════════════════════════════════════════════════ */

/* Métadonnées d'affichage des secteurs (ordre = ordre des hubs). */
export const SECTORS = [
  { slug: 'restauration',        label: 'Restauration',            emoji: '🍽️', noun: 'restaurant' },
  { slug: 'tourisme-hebergement', label: 'Tourisme & hébergement', emoji: '🏝️', noun: 'hébergement touristique' },
  { slug: 'batiment-artisans',   label: 'Bâtiment & artisans',     emoji: '🏗️', noun: 'entreprise du bâtiment' },
];

/* Contenu éditorial. Chaque entrée :
   { title, desc, keywords, tag, h1, lead, sections:[{h2, html}], callout, faq:[{q,a}] } */
export const CONTENT = {

  /* ═════════════════ RESTAURATION ═════════════════ */
  restauration: {
    guadeloupe: {
      title: "Créer un site internet pour un restaurant en Guadeloupe",
      desc: "Restaurant, snack, lolo ou traiteur en Guadeloupe : comment un site web et Google captent la clientèle locale et les touristes. Guide GroupSolution, site vitrine dès 250€.",
      keywords: "site internet restaurant Guadeloupe, référencement restaurant 971, menu en ligne Guadeloupe, réservation restaurant Le Gosier, Google restaurant Pointe-à-Pitre, création site lolo",
      tag: "Restauration · Guadeloupe",
      h1: "Site internet pour un restaurant en Guadeloupe : capter les locaux et les touristes",
      lead: "Du lolo de bord de plage au restaurant gastronomique de Saint-François, la restauration guadeloupéenne vit d'une double clientèle : les habitants fidèles et les visiteurs de passage. Aujourd'hui, les deux commencent leur choix sur leur téléphone.",
      sections: [
        { h2: "Une clientèle qui cherche d'abord sur Google et Maps",
          html: "<p>En Guadeloupe, un touriste métropolitain qui arrive au Gosier ou à Sainte-Anne tape « restaurant près de moi » ou « meilleur bokit Grande-Terre » avant même de sortir. S'il ne vous trouve pas — avec vos photos, vos horaires, votre carte et vos avis — il va chez le voisin. Un site rapide couplé à une fiche <strong>Google Business Profile</strong> soignée est aujourd'hui votre première salle d'attente.</p><p>Pour la clientèle locale, c'est pareil : on vérifie si vous êtes ouvert le dimanche, si vous faites à emporter, si le court-bouillon est au menu ce midi. Répondre à ces questions en ligne, c'est déjà remplir des tables.</p>" },
        { h2: "Ce qui fait réserver : carte, photos, avis",
          html: "<ul><li><strong>Une carte à jour</strong> et lisible sur mobile (plus de menu PDF illisible qui met 10 secondes à charger).</li><li><strong>De vraies photos</strong> de vos plats et de la salle : c'est ce qui déclenche l'envie et distingue un restaurant d'un autre.</li><li><strong>Les avis Google</strong> mis en avant et entretenus : en zone touristique, la note compte autant que l'emplacement.</li><li><strong>Le clic-pour-appeler</strong> et l'itinéraire Maps, indispensables pour un client déjà en voiture.</li></ul>" },
        { h2: "À emporter, réservation, livraison : garder la main",
          html: "<p>Beaucoup de restaurateurs passent par les plateformes de livraison et leurs commissions. Un site à vous permet de proposer la réservation ou la commande à emporter <strong>en direct</strong>, sans reverser 20 à 30 % à un intermédiaire. On met en place un formulaire de réservation simple, relié à votre téléphone ou votre e-mail, sans usine à gaz.</p>" },
        { h2: "Notre approche pour la restauration antillaise",
          html: "<p>On conçoit un site vitrine clair, taillé pour le mobile et la recherche locale, avec votre carte, vos photos, vos horaires et un bouton de contact direct. On raccorde le tout à votre fiche Google pour que vous remontiez sur « restaurant + votre ville ». Un site vitrine professionnel démarre à 250€, et on vous forme pour changer votre carte vous-même.</p>" },
      ],
      callout: "En Guadeloupe, la saison touristique haute (décembre-avril) concentre une part énorme du chiffre. Un restaurant bien référencé capte cette clientèle de passage qui, elle, ne vous connaît pas encore : tout se joue en ligne.",
      faq: [
        { q: "J'ai déjà une page Facebook, pourquoi un site en plus ?", a: "Facebook est parfait pour animer votre communauté, mais il n'apparaît pas quand un touriste tape « restaurant Le Gosier » sur Google. Un site + une fiche Google vous rendent visibles au moment exact du choix, et vous appartiennent — contrairement à une page qui dépend d'un algorithme." },
        { q: "Combien coûte un site pour mon restaurant en Guadeloupe ?", a: "Un site vitrine professionnel (carte, photos, horaires, contact, optimisé mobile et Google) démarre à 250€. Si vous voulez la réservation en ligne ou la commande à emporter, on chiffre selon vos besoins, toujours avec un devis clair." },
        { q: "Puis-je changer ma carte moi-même ?", a: "Oui. On construit le site pour que vous puissiez mettre à jour votre menu, vos plats du jour et vos horaires sans nous rappeler, et on vous forme lors de la livraison." },
        { q: "Est-ce utile si je fais surtout du sur-place avec des habitués ?", a: "Oui : même une clientèle fidèle vérifie vos horaires, votre menu et si vous faites à emporter en ligne. Et une bonne présence Google vous amène en continu les nouveaux arrivants et les touristes du secteur." },
      ],
    },

    reunion: {
      title: "Créer un site internet pour un restaurant à La Réunion",
      desc: "Restaurant, snack, camion-bar ou table créole à La Réunion : comment un site web et Google remplissent la salle, côté locaux comme touristes. Guide GroupSolution, dès 250€.",
      keywords: "site internet restaurant Réunion, référencement restaurant 974, menu en ligne Saint-Gilles, réservation restaurant Saint-Denis, Google restaurant Saint-Pierre, création site snack créole",
      tag: "Restauration · La Réunion",
      h1: "Site internet pour un restaurant à La Réunion : remplir la salle, locaux et touristes",
      lead: "Du camion-bar posé face au lagon de Saint-Gilles à la table créole de Cilaos, la restauration réunionnaise vit d'une clientèle multiple : habitants fidèles, touristes de métropole et voyageurs de l'océan Indien. Tous commencent leur choix sur leur téléphone.",
      sections: [
        { h2: "La recherche locale décide où l'on mange",
          html: "<p>Un visiteur qui séjourne dans l'Ouest tape « restaurant Saint-Gilles » ou « meilleur cari à La Réunion » ; un Réunionnais vérifie si vous êtes ouvert le dimanche midi et si vous faites à emporter. Sans site ni fiche <strong>Google Business Profile</strong> à jour, vous êtes invisible au moment précis de la décision.</p>" },
        { h2: "Ce qui fait entrer les clients",
          html: "<ul><li><strong>Une carte lisible sur mobile</strong> — cari, rougail, samoussas, bouchons — plutôt qu'un PDF interminable.</li><li><strong>De belles photos</strong> de vos plats et de la vue.</li><li><strong>Vos avis Google</strong> mis en avant et entretenus.</li><li><strong>Le clic-pour-appeler</strong> et l'itinéraire, pour le client déjà en voiture.</li></ul>" },
        { h2: "À emporter et réservation en direct",
          html: "<p>Plutôt que de reverser 20 à 30 % de commission à une plateforme de livraison, un site à vous permet la réservation et la commande à emporter <strong>en direct</strong>. Un formulaire simple relié à votre téléphone suffit pour garder la main sur votre marge et votre clientèle.</p>" },
        { h2: "Notre approche pour la restauration créole",
          html: "<p>On crée un site vitrine clair, pensé mobile et recherche locale : carte, photos, horaires, contact direct, le tout raccordé à votre fiche Google pour remonter sur « restaurant + votre ville ». Site vitrine dès 250€, avec formation pour gérer votre carte en autonomie.</p>" },
      ],
      callout: "La haute saison touristique — l'hiver austral (juillet-août) et les fêtes — amène une clientèle de passage qui ne vous connaît pas encore. Tout se joue alors en ligne : elle choisit ce qu'elle trouve, pas ce qu'elle ignore.",
      faq: [
        { q: "J'ai déjà une page Facebook, pourquoi un site ?", a: "Facebook anime vos habitués, mais n'apparaît pas quand un touriste tape « restaurant Saint-Gilles » sur Google. Un site + une fiche Google vous rendent visibles au moment du choix, et vous appartiennent." },
        { q: "Combien coûte un site pour mon restaurant à La Réunion ?", a: "Un site vitrine professionnel (carte, photos, horaires, contact, optimisé mobile et Google) démarre à 250€. Pour la réservation ou la commande à emporter en ligne, on chiffre selon vos besoins." },
        { q: "Puis-je changer ma carte moi-même ?", a: "Oui. On construit le site pour que vous mettiez à jour menu, plats du jour et horaires sans nous rappeler, et on vous forme à la livraison." },
        { q: "Est-ce utile si je vis surtout des habitués ?", a: "Oui : même fidèle, un client vérifie vos horaires et votre carte en ligne. Et une bonne présence Google vous amène en continu les nouveaux arrivants et les touristes du secteur." },
      ],
    },

    mayotte: {
      title: "Créer un site internet pour un restaurant à Mayotte",
      desc: "Restaurant, snack, brochetterie ou voulé à Mayotte : comment un site web et Google captent une clientèle jeune et connectée. Guide GroupSolution, site vitrine dès 250€.",
      keywords: "site internet restaurant Mayotte, référencement restaurant 976, menu en ligne Mamoudzou, snack Petite-Terre, Google restaurant Mayotte, création site brochetterie",
      tag: "Restauration · Mayotte",
      h1: "Site internet pour un restaurant à Mayotte : capter une clientèle jeune et connectée",
      lead: "Snacks de Mamoudzou, brochetteries, voulés de bord de mer le week-end : la restauration mahoraise s'adresse à une population jeune, en forte croissance et très présente sur son téléphone. Peu d'établissements sont pourtant visibles sur Google.",
      sections: [
        { h2: "Un marché jeune, connecté et sous-équipé en ligne",
          html: "<p>À Mayotte, on cherche où manger sur son smartphone, mais rares sont les restaurants avec une vraie présence en ligne. Celui qui apparaît le premier sur « restaurant Mamoudzou » ou « snack Petite-Terre », avec photos et horaires, prend une longueur d'avance sur toute la concurrence.</p>" },
        { h2: "Ce qui donne envie de venir",
          html: "<ul><li><strong>Vos plats en photos</strong> — mataba, poulet coco, mabawa, brochettes.</li><li><strong>Horaires et jours d'ouverture</strong> clairs, y compris pour les voulés du week-end.</li><li><strong>Un contact direct</strong> (appel, WhatsApp) et l'itinéraire.</li><li><strong>Les avis</strong>, encore rares à Mayotte : les collecter tôt vous démarque durablement.</li></ul>" },
        { h2: "Au-delà de Facebook et WhatsApp",
          html: "<p>Facebook et WhatsApp dominent les échanges à Mayotte, mais ne vous placent pas dans les recherches Google. Un site simple, couplé à votre fiche Google, complète vos réseaux et capte ceux qui cherchent activement où manger — nouveaux arrivants, professionnels de passage, familles.</p>" },
        { h2: "Notre approche pour la restauration mahoraise",
          html: "<p>On met en place un site vitrine léger et rapide, pensé mobile, avec votre carte, vos photos et un contact direct, raccordé à Google. Objectif : être trouvé et donner envie, sans complexité. Site vitrine dès 250€.</p>" },
      ],
      callout: "Mayotte est le département le plus jeune de France : une clientèle nombreuse et connectée qui découvre les commerces sur son téléphone. Prendre sa place en ligne maintenant, c'est s'installer avant la concurrence.",
      faq: [
        { q: "À Mayotte tout passe par WhatsApp, un site sert-il vraiment ?", a: "WhatsApp est parfait pour échanger avec vos clients, mais personne ne vous y découvre. Un site + une fiche Google vous rendent trouvables quand quelqu'un cherche « restaurant Mamoudzou », puis le renvoie vers votre WhatsApp pour commander." },
        { q: "Combien coûte un site pour mon restaurant à Mayotte ?", a: "Un site vitrine professionnel optimisé mobile et Google démarre à 250€, avec un devis clair si vous voulez aller plus loin (commande, menu détaillé)." },
        { q: "La connexion est parfois lente, est-ce un problème ?", a: "Non : on conçoit des sites légers qui chargent vite même en réseau limité, justement pour rester efficaces dans les conditions locales." },
        { q: "Puis-je gérer le site moi-même ?", a: "Oui, on vous forme pour mettre à jour carte, photos et horaires en autonomie." },
      ],
    },

    guyane: {
      title: "Créer un site internet pour un restaurant en Guyane",
      desc: "Restaurant, table métissée ou snack en Guyane : comment un site web et Google captent locaux, touristes et travailleurs du spatial. Guide GroupSolution, dès 250€.",
      keywords: "site internet restaurant Guyane, référencement restaurant 973, menu en ligne Cayenne, restaurant Kourou, Google restaurant Guyane, création site snack Cayenne",
      tag: "Restauration · Guyane",
      h1: "Site internet pour un restaurant en Guyane : une cuisine métissée à faire connaître",
      lead: "Créole, bushinengue, hmong, brésilienne, chinoise : la Guyane est une mosaïque culinaire unique. Du marché de Cayenne aux tables de Kourou, cette richesse est un argument — encore faut-il qu'on la trouve en ligne.",
      sections: [
        { h2: "Une clientèle variée qui cherche sur Google",
          html: "<p>Touristes en écotourisme, familles, cadres et travailleurs du Centre spatial à Kourou : la clientèle guyanaise est diverse et mobile. Elle tape « restaurant Cayenne », « où manger Kourou » ou une spécialité précise. Sans présence en ligne, vous passez sous le radar.</p>" },
        { h2: "Mettre en valeur votre spécialité",
          html: "<ul><li><strong>Votre identité culinaire</strong> clairement affichée — bouillon d'awara, poisson, cuisine hmong, brésilienne…</li><li><strong>Des photos</strong> qui donnent envie et racontent votre table.</li><li><strong>Horaires, à emporter, contact direct.</strong></li><li><strong>Les avis Google</strong>, décisifs pour une clientèle de passage.</li></ul>" },
        { h2: "Garder la main sur vos commandes",
          html: "<p>Un site à vous permet la commande à emporter et la réservation en direct, sans commission de plateforme. Pratique pour capter la clientèle professionnelle de Kourou et de Cayenne qui commande souvent le midi.</p>" },
        { h2: "Notre approche pour la restauration guyanaise",
          html: "<p>On crée un site vitrine clair et rapide, pensé mobile et recherche locale, raccordé à votre fiche Google pour remonter sur « restaurant + votre ville ». Site vitrine dès 250€, avec autonomie sur votre carte.</p>" },
      ],
      callout: "La diversité culinaire guyanaise est un vrai atout marketing : une table qui affiche clairement son identité — et la rend visible sur Google — se démarque immédiatement auprès des curieux et des touristes.",
      faq: [
        { q: "Facebook me suffit-il pour mon restaurant en Guyane ?", a: "Facebook fidélise, mais n'apparaît pas sur « restaurant Cayenne » dans Google. Un site + fiche Google vous rendent visibles au moment du choix, y compris pour les visiteurs et travailleurs de passage." },
        { q: "Combien coûte un site pour mon restaurant en Guyane ?", a: "Un site vitrine professionnel démarre à 250€. Réservation ou commande à emporter en ligne : devis clair selon vos besoins." },
        { q: "Je vise surtout la clientèle de Kourou, est-ce adapté ?", a: "Oui : on optimise pour « restaurant Kourou » et la commande du midi, très demandée par la clientèle professionnelle du secteur spatial." },
        { q: "Puis-je modifier ma carte seul ?", a: "Oui, on vous forme pour gérer carte, photos et horaires en toute autonomie." },
      ],
    },

    martinique: {
      title: "Créer un site internet pour un restaurant en Martinique",
      desc: "Restaurant, table créole ou snack en Martinique : comment un site web et Google captent locaux, touristes et croisiéristes. Guide GroupSolution, site vitrine dès 250€.",
      keywords: "site internet restaurant Martinique, référencement restaurant 972, menu en ligne Fort-de-France, restaurant croisière Martinique, Google restaurant Schoelcher, création site table créole",
      tag: "Restauration · Martinique",
      h1: "Site internet pour un restaurant en Martinique : locaux, touristes et croisiéristes",
      lead: "Accras, colombo, ti-punch et gastronomie créole : la table martiniquaise est un pilier du séjour. Entre habitants, touristes de métropole et escales de croisière à Fort-de-France, la clientèle est large — et elle choisit sur son téléphone.",
      sections: [
        { h2: "Le croisiériste et le touriste décident en ligne, vite",
          html: "<p>Une escale de croisière ne dure que quelques heures : le passager cherche « restaurant Fort-de-France » et lit les avis avant de descendre. Le touriste en séjour compare les tables du sud balnéaire. Sans présence en ligne soignée, vous n'êtes pas dans la course.</p>" },
        { h2: "Ce qui remplit une table en Martinique",
          html: "<ul><li><strong>Une carte à jour</strong> et des photos qui mettent en valeur la cuisine créole.</li><li><strong>Vos avis Google</strong>, souvent décisifs pour une clientèle de passage.</li><li><strong>Horaires, à emporter, itinéraire, clic-appel.</strong></li><li>Une version <strong>lisible en anglais</strong> pour les croisiéristes, un vrai plus.</li></ul>" },
        { h2: "Réservation et à emporter en direct",
          html: "<p>Un site à vous permet de prendre réservations et commandes sans commission de plateforme, et de fidéliser une clientèle qui revient d'une saison à l'autre.</p>" },
        { h2: "Notre approche pour la restauration martiniquaise",
          html: "<p>Site vitrine clair, mobile-first, raccordé à Google pour remonter sur « restaurant + votre ville », avec autonomie sur la carte. Dès 250€.</p>" },
      ],
      callout: "Les escales de croisière à Fort-de-France déversent une clientèle qui choisit son restaurant en quelques minutes, sur Google, avis à l'appui. Être bien référencé ces jours-là, c'est remplir la salle.",
      faq: [
        { q: "Une page Facebook ne suffit-elle pas ?", a: "Elle fidélise vos habitués, mais n'apparaît pas sur « restaurant Fort-de-France » dans Google, là où décident touristes et croisiéristes. Le site + la fiche Google, oui." },
        { q: "Combien coûte un site pour mon restaurant en Martinique ?", a: "À partir de 250€ pour un site vitrine professionnel ; devis clair pour la réservation ou la commande en ligne." },
        { q: "Faut-il une version anglaise ?", a: "Pour capter les croisiéristes, une carte et des infos lisibles en anglais sont un vrai atout ; on peut le prévoir." },
        { q: "Puis-je gérer ma carte moi-même ?", a: "Oui, formation incluse pour mettre à jour carte, photos et horaires en autonomie." },
      ],
    },

    'nouvelle-caledonie': {
      title: "Créer un site internet pour un restaurant en Nouvelle-Calédonie",
      desc: "Restaurant, roulotte ou table calédonienne à Nouméa et alentours : comment un site web et Google captent une clientèle urbaine, expatriée et de croisière. GroupSolution, dès 250€.",
      keywords: "site internet restaurant Nouvelle-Calédonie, référencement restaurant Nouméa, menu en ligne 988, restaurant croisière Nouméa, Google restaurant Dumbéa, création site table calédonienne",
      tag: "Restauration · Nouvelle-Calédonie",
      h1: "Site internet pour un restaurant en Nouvelle-Calédonie : se démarquer à Nouméa et au-delà",
      lead: "Bougna, cuisine française, tables vietnamiennes, indonésiennes et japonaises : Nouméa est une scène culinaire dense qui sert une clientèle urbaine, expatriée et de croisière. Dans cette concurrence, la visibilité en ligne fait la différence.",
      sections: [
        { h2: "Une clientèle exigeante qui compare en ligne",
          html: "<p>À Nouméa, Dumbéa ou au Mont-Dore, on choisit son restaurant sur Google — avis, photos, carte à l'appui. Les croisiéristes de passage à Nouméa font pareil, en quelques minutes. Sans présence soignée, difficile d'exister face à une offre abondante.</p>" },
        { h2: "Ce qui fait la différence",
          html: "<ul><li><strong>Des photos soignées</strong> et une carte à jour.</li><li><strong>Vos avis Google</strong>, très regardés par une clientèle au fort pouvoir d'achat.</li><li><strong>Réservation, à emporter, clic-appel, itinéraire.</strong></li><li>Une lisibilité <strong>en anglais</strong> pour les croisiéristes et les touristes australiens et néo-zélandais.</li></ul>" },
        { h2: "Réserver et commander en direct",
          html: "<p>Un site à vous capte la réservation directe et la commande du midi (clientèle de bureaux à Nouméa), sans commission de plateforme.</p>" },
        { h2: "Notre approche pour la restauration calédonienne",
          html: "<p>Site vitrine élégant, mobile-first, raccordé à Google pour « restaurant + votre commune », avec autonomie sur la carte. Dès 250€.</p>" },
      ],
      callout: "Nouméa concentre une clientèle urbaine au pouvoir d'achat élevé et des escales de croisière régulières. Dans une offre aussi dense, le restaurant le mieux présenté en ligne rafle les nouvelles tables.",
      faq: [
        { q: "La concurrence est forte à Nouméa, un site change-t-il vraiment la donne ?", a: "Oui : à offre égale, le client choisit le restaurant dont les photos, la carte et les avis le convainquent en ligne. C'est souvent là que se joue la première visite." },
        { q: "Combien coûte un site pour mon restaurant en Nouvelle-Calédonie ?", a: "À partir de 250€ pour un site vitrine professionnel ; devis clair pour réservation ou commande en ligne." },
        { q: "Faut-il une version anglaise ?", a: "Pour la clientèle de croisière et australienne/néo-zélandaise, c'est un vrai atout ; on peut prévoir une version bilingue." },
        { q: "Puis-je gérer ma carte moi-même ?", a: "Oui, on vous forme pour tout mettre à jour en autonomie." },
      ],
    },

    'polynesie-francaise': {
      title: "Créer un site internet pour un restaurant en Polynésie française",
      desc: "Restaurant, roulotte ou table tahitienne à Papeete, Bora-Bora ou Moorea : comment un site web et Google captent une clientèle touristique internationale. GroupSolution, dès 250€.",
      keywords: "site internet restaurant Polynésie, référencement restaurant Tahiti, menu en ligne Papeete, roulotte Papeete, Google restaurant Bora-Bora, création site table tahitienne",
      tag: "Restauration · Polynésie française",
      h1: "Site internet pour un restaurant en Polynésie : séduire une clientèle internationale",
      lead: "Poisson cru au lait de coco, roulottes de la place Vaiete, tables de Bora-Bora et Moorea : la restauration polynésienne sert une clientèle très internationale, souvent haut de gamme, qui prépare son séjour — et ses repas — en ligne.",
      sections: [
        { h2: "Une clientèle qui réserve avant même d'arriver",
          html: "<p>Le voyageur en route pour Tahiti, Moorea ou Bora-Bora repère ses restaurants sur Google bien avant le décollage. S'il ne vous trouve pas — en anglais, avec photos et avis — il réserve ailleurs. La visibilité en ligne se joue en amont du séjour.</p>" },
        { h2: "Ce qui déclenche la réservation",
          html: "<ul><li><strong>Des photos superbes</strong> de vos plats et du cadre (lagon, coucher de soleil).</li><li><strong>Une carte claire</strong>, idéalement <strong>bilingue français/anglais</strong>.</li><li><strong>Vos avis</strong>, scrutés par une clientèle internationale.</li><li><strong>Réservation et contact directs.</strong></li></ul>" },
        { h2: "Capter la réservation en direct",
          html: "<p>Face aux hôtels et aux plateformes, un site à vous — bilingue — capte la réservation directe du touriste comme du résident, sans commission, et valorise votre table au-delà de votre île.</p>" },
        { h2: "Notre approche pour la restauration polynésienne",
          html: "<p>Site vitrine soigné, mobile-first et bilingue si besoin, raccordé à Google pour « restaurant + Papeete/Bora-Bora… », avec autonomie sur la carte. Dès 250€.</p>" },
      ],
      callout: "En Polynésie, une grande partie de la clientèle est internationale et haut de gamme : elle choisit ses restaurants en ligne, en anglais, avant l'arrivée. Un site bilingue soigné capte cette réservation que les autres laissent filer.",
      faq: [
        { q: "Ma clientèle est surtout touristique, un site est-il prioritaire ?", a: "C'est justement pour elle qu'il est essentiel : le touriste prépare tout en ligne avant de venir. Un site bilingue avec photos et avis capte sa réservation en amont du séjour." },
        { q: "Combien coûte un site pour mon restaurant en Polynésie ?", a: "À partir de 250€ pour un site vitrine professionnel ; version bilingue et réservation en ligne sur devis clair." },
        { q: "Le bilingue français/anglais est-il vraiment utile ?", a: "Oui, indispensable ici : une large part de vos clients sont anglophones. On prévoit une version anglaise pour ne perdre personne." },
        { q: "Puis-je gérer ma carte moi-même ?", a: "Oui, formation incluse pour mettre à jour la carte, les photos et les horaires." },
      ],
    },
  },

  /* ═════════════════ TOURISME & HÉBERGEMENT ═════════════════ */
  'tourisme-hebergement': {
    guadeloupe: {
      title: "Site internet pour un hébergement touristique en Guadeloupe",
      desc: "Gîte, location saisonnière, meublé ou chambre d'hôtes en Guadeloupe : un site de réservation directe pour échapper aux commissions Airbnb/Booking. Guide GroupSolution, dès 250€.",
      keywords: "site internet gîte Guadeloupe, location saisonnière 971, réservation directe hébergement Guadeloupe, meublé de tourisme Sainte-Anne, site chambre d'hôtes Basse-Terre, éviter commissions Airbnb",
      tag: "Tourisme & hébergement · Guadeloupe",
      h1: "Hébergement touristique en Guadeloupe : votre site de réservation directe",
      lead: "Gîtes de Basse-Terre, meublés de Grande-Terre, chambres d'hôtes des Saintes : la Guadeloupe vit largement du tourisme. Mais chaque réservation passée par une plateforme vous coûte 15 à 25 % de commission. Un site à vous change l'équation.",
      sections: [
        { h2: "Le vrai coût des plateformes",
          html: "<p>Airbnb, Booking et les autres apportent de la visibilité, mais prélèvent une commission sur chaque nuitée et gardent la relation client. Sur une saison complète, ces commissions représentent souvent plusieurs milliers d'euros. Un site de réservation directe ne les fait pas disparaître du jour au lendemain, mais il vous permet de <strong>récupérer les clients qui reviennent</strong> et ceux qui vous ont trouvé par le bouche-à-oreille — sans reverser un centime.</p>" },
        { h2: "Ce qu'attend un voyageur avant de réserver",
          html: "<ul><li>Des <strong>photos qui donnent envie</strong> : la vue, la piscine, la plage à 5 minutes, la terrasse au coucher du soleil.</li><li>Les <strong>infos pratiques</strong> claires : capacité, équipements, distance des sites (plages, Soufrière, plongée), conditions.</li><li>La <strong>confiance</strong> : avis, présentation des hôtes, réponses rapides.</li><li>Un <strong>contact direct</strong> et une demande de disponibilité simples, en français comme en anglais si vous visez l'international.</li></ul>" },
        { h2: "Se rendre visible sur les recherches touristiques",
          html: "<p>Les voyageurs cherchent « location vue mer Sainte-Anne », « gîte Soufrière avec piscine », « où dormir aux Saintes ». Un site bien optimisé sur ces requêtes locales vous positionne en dehors des plateformes, là où la concurrence est moins féroce et où vous captez le voyageur qui veut réserver en direct.</p>" },
        { h2: "Notre approche pour l'hébergement en Guadeloupe",
          html: "<p>On crée un site vitrine élégant qui met en valeur votre bien, avec galerie photo, descriptif, atouts du secteur et formulaire de demande de réservation. Objectif : transformer un site vitrine (dès 250€) en canal de réservation directe qui, saison après saison, réduit votre dépendance aux commissions.</p>" },
      ],
      callout: "La clientèle métropolitaine réserve souvent son séjour d'hiver dès l'automne. Être visible et crédible en ligne à ce moment-là — avec un vrai site, pas seulement une annonce — fait la différence entre une saison pleine et une saison à trous.",
      faq: [
        { q: "Un site va-t-il vraiment remplacer Airbnb et Booking ?", a: "Pas du jour au lendemain, et ce n'est pas le but. Les plateformes restent utiles pour la découverte. Votre site sert à capter les réservations directes — clients fidèles, recommandations, voyageurs qui préfèrent traiter avec vous — et donc à récupérer les commissions sur cette part-là." },
        { q: "Combien coûte un site pour mon gîte ou ma location en Guadeloupe ?", a: "Un site vitrine professionnel avec galerie photo et formulaire de demande démarre à 250€. Pour un moteur de réservation avec calendrier et paiement en ligne, on établit un devis selon vos besoins." },
        { q: "Je loue un seul bien, est-ce que ça vaut le coup ?", a: "Oui. Même pour un seul gîte, quelques réservations directes par an récupérées sur les commissions amortissent largement le site, et vous construisez un actif qui vous appartient." },
        { q: "Pouvez-vous faire un site en français et en anglais ?", a: "Oui, c'est recommandé si vous visez la clientèle internationale. On peut prévoir une version bilingue pour ne pas perdre les voyageurs anglophones." },
      ],
    },

    reunion: {
      title: "Site internet pour un hébergement touristique à La Réunion",
      desc: "Gîte de montagne, location de l'Ouest ou chambre d'hôtes à La Réunion : un site de réservation directe pour capter randonneurs et vacanciers, sans commissions. GroupSolution, dès 250€.",
      keywords: "site internet gîte Réunion, location saisonnière 974, réservation directe hébergement Réunion, gîte Mafate Cilaos, chambre d'hôtes Saint-Gilles, éviter commissions Airbnb Réunion",
      tag: "Tourisme & hébergement · La Réunion",
      h1: "Hébergement touristique à La Réunion : votre site de réservation directe",
      lead: "Gîtes de Mafate et Cilaos, locations face au lagon de Saint-Gilles, chambres d'hôtes des Hauts : La Réunion attire randonneurs et vacanciers toute l'année. Mais chaque réservation via une plateforme ampute votre marge. Un site à vous rééquilibre le jeu.",
      sections: [
        { h2: "Le vrai coût des plateformes",
          html: "<p>Les plateformes apportent de la visibilité mais prélèvent 15 à 25 % par réservation et gardent la relation client. Sur une saison, cela représente vite plusieurs milliers d'euros. Un site de réservation directe vous permet de <strong>récupérer les clients fidèles et le bouche-à-oreille</strong> sans reverser un centime.</p>" },
        { h2: "Ce que cherche un voyageur pour La Réunion",
          html: "<ul><li><strong>Des photos qui donnent envie</strong> : la vue sur le cirque, le lagon, la terrasse.</li><li><strong>Les infos pratiques</strong> : accès (Mafate à pied), proximité des sentiers et des plages, capacité, équipements.</li><li><strong>La confiance</strong> : avis, présentation des hôtes, réponses rapides.</li><li><strong>Un contact et une demande de disponibilité</strong> simples.</li></ul>" },
        { h2: "Être visible sur les recherches touristiques",
          html: "<p>Les voyageurs tapent « gîte Mafate », « location vue mer Saint-Gilles », « chambre d'hôtes Cilaos ». Un site optimisé sur ces requêtes vous positionne hors des plateformes, là où vous captez le voyageur qui veut réserver en direct.</p>" },
        { h2: "Notre approche pour l'hébergement réunionnais",
          html: "<p>On crée un site vitrine élégant qui met en valeur votre bien : galerie photo, descriptif, atouts du secteur, formulaire de demande. Dès 250€, avec l'objectif de réduire, saison après saison, votre dépendance aux commissions.</p>" },
      ],
      callout: "Mafate ne se rejoint qu'à pied ou en hélicoptère : ses gîtes se réservent presque tous en direct. Un site clair et bien référencé y est tout simplement vital pour remplir ses nuitées.",
      faq: [
        { q: "Un site va-t-il remplacer les plateformes ?", a: "Pas du jour au lendemain, et ce n'est pas le but : elles restent utiles pour la découverte. Votre site capte les réservations directes — fidèles, recommandations — et récupère les commissions sur cette part." },
        { q: "Combien coûte un site pour mon gîte à La Réunion ?", a: "Un site vitrine avec galerie et formulaire de demande démarre à 250€. Pour un calendrier et un paiement en ligne, devis selon vos besoins." },
        { q: "Je n'ai qu'un seul bien, est-ce rentable ?", a: "Oui : quelques réservations directes par an récupérées sur les commissions amortissent largement le site, et vous construisez un actif qui vous appartient." },
        { q: "Faut-il une version en anglais ?", a: "Utile si vous visez la clientèle de la zone océan Indien ou internationale ; on peut prévoir une version bilingue." },
      ],
    },

    mayotte: {
      title: "Site internet pour un hébergement touristique à Mayotte",
      desc: "Gîte, pension ou location à Mayotte : un site pour capter plongeurs, naturalistes et voyageurs qui préparent tout en ligne. Réservation directe, sans commissions. GroupSolution, dès 250€.",
      keywords: "site internet gîte Mayotte, hébergement touristique 976, réservation directe Mayotte, pension lagon Mayotte, plongée baleines Mayotte, location Petite-Terre",
      tag: "Tourisme & hébergement · Mayotte",
      h1: "Hébergement touristique à Mayotte : capter une clientèle de niche qui prépare tout en ligne",
      lead: "Le lagon de Mayotte, l'un des plus grands lagons fermés au monde, ses baleines à bosse, ses tortues et sa mangrove attirent une clientèle de plongeurs et de naturalistes. L'offre d'hébergement structurée reste rare : une place est à prendre en ligne.",
      sections: [
        { h2: "Une clientèle qui organise son séjour à distance",
          html: "<p>On ne vient pas à Mayotte par hasard : plongeurs, amateurs de nature et professionnels planifient leur venue des semaines à l'avance, sur Internet. S'ils ne trouvent pas votre gîte ou votre pension en ligne, ils réservent l'un des rares établissements visibles — pas le vôtre.</p>" },
        { h2: "Ce qui rassure et fait réserver",
          html: "<ul><li><strong>Des photos</strong> du lagon, de la vue, du logement.</li><li><strong>Les atouts du secteur</strong> : accès plongée, mangrove, plages, sorties baleines en saison.</li><li><strong>Infos pratiques et confiance</strong> : capacité, équipements, présentation des hôtes.</li><li><strong>Un contact direct</strong> pour réserver sans intermédiaire.</li></ul>" },
        { h2: "Prendre l'avantage dans un marché émergent",
          html: "<p>L'offre en ligne étant encore limitée à Mayotte, un site bien fait vous place devant sur « hébergement Mayotte », « gîte lagon Mayotte » ou « où dormir Petite-Terre ». C'est le bon moment pour occuper le terrain.</p>" },
        { h2: "Notre approche pour l'hébergement mahorais",
          html: "<p>On crée un site vitrine soigné et rapide qui met en valeur votre bien et l'expérience unique du lagon, avec galerie et formulaire de demande. Dès 250€.</p>" },
      ],
      callout: "Le lagon et les baleines de Mayotte attirent une clientèle de niche — plongeurs, naturalistes — qui organise tout en ligne avant de venir. Avec une offre encore rare, être visible aujourd'hui, c'est prendre une place difficile à déloger.",
      faq: [
        { q: "Le tourisme est encore modeste à Mayotte, est-ce le bon moment ?", a: "Oui, justement : peu d'hébergements sont visibles en ligne. Prendre position maintenant vous installe en tête avant que le marché ne se structure et que la concurrence n'arrive." },
        { q: "Combien coûte un site pour mon hébergement à Mayotte ?", a: "Un site vitrine avec galerie et formulaire de demande démarre à 250€, avec un devis clair pour aller plus loin." },
        { q: "Faut-il une version en anglais ?", a: "Un plus pour les plongeurs et naturalistes internationaux ; on peut prévoir une version bilingue." },
        { q: "Je débute dans la location, est-ce adapté ?", a: "Oui : on construit un site simple à gérer, et on vous forme pour mettre à jour photos, disponibilités et infos vous-même." },
      ],
    },

    guyane: {
      title: "Site internet pour un hébergement ou un écolodge en Guyane",
      desc: "Carbet, lodge, gîte ou hébergement en Guyane : un site pour vendre l'expérience amazonienne et capter la réservation directe. GroupSolution, site vitrine dès 250€.",
      keywords: "site internet écolodge Guyane, hébergement touristique 973, carbet forêt Guyane, réservation directe Guyane, gîte fleuve Maroni, tourisme îles du Salut",
      tag: "Tourisme & hébergement · Guyane",
      h1: "Hébergement touristique en Guyane : vendre l'expérience amazonienne en ligne",
      lead: "Carbets au cœur de la forêt, lodges au bord du Maroni ou de l'Approuague, gîtes proches des îles du Salut : l'écotourisme guyanais se vend d'abord par l'image et le récit. C'est en ligne que le voyageur choisit son aventure.",
      sections: [
        { h2: "L'écotouriste se décide sur l'expérience",
          html: "<p>Celui qui vient en Guyane cherche une expérience : nuit en carbet, remontée de fleuve, observation de la faune. Il la choisit sur Internet, séduit par des photos et un récit. Sans site pour raconter votre lieu, votre offre reste invisible, aussi belle soit-elle.</p>" },
        { h2: "Ce qui transforme le curieux en client",
          html: "<ul><li><strong>Des photos immersives</strong> : forêt, fleuve, carbet, faune.</li><li><strong>Le récit de l'expérience</strong> : ce qu'on vit, ce qu'on voit, comment on accède.</li><li><strong>Infos pratiques</strong> : capacité, saison, transferts, ce qui est inclus.</li><li><strong>Un contact direct</strong> pour réserver sans intermédiaire.</li></ul>" },
        { h2: "Se positionner sur l'écotourisme",
          html: "<p>Un site optimisé sur « écolodge Guyane », « carbet forêt Guyane » ou « hébergement fleuve Maroni » vous place devant une clientèle motivée — écotouristes, familles, mais aussi tourisme d'affaires lié au spatial.</p>" },
        { h2: "Notre approche pour l'hébergement guyanais",
          html: "<p>On crée un site vitrine immersif qui met en scène votre lieu et l'expérience proposée, avec galerie, récit et formulaire de demande. Dès 250€.</p>" },
      ],
      callout: "L'écotourisme guyanais se vend par l'émotion : un site qui raconte l'expérience — le carbet, le fleuve, la faune — transforme le curieux en voyageur, là où une simple annonce ne dit rien.",
      faq: [
        { q: "Les plateformes ne suffisent-elles pas pour mon lodge ?", a: "Elles listent, mais ne racontent pas votre expérience et prélèvent une commission. Un site à vous met en scène votre lieu, capte la réservation directe et vous fait remonter sur Google." },
        { q: "Combien coûte un site pour mon hébergement en Guyane ?", a: "Un site vitrine immersif avec galerie et formulaire démarre à 250€ ; devis clair pour un calendrier ou un paiement en ligne." },
        { q: "Mon activité est saisonnière, est-ce utile toute l'année ?", a: "Oui : le voyageur prépare souvent son séjour plusieurs mois à l'avance. Un site visible en continu capte ces réservations anticipées." },
        { q: "Faut-il une version anglaise ?", a: "Un atout pour la clientèle internationale d'écotourisme ; on peut prévoir une version bilingue." },
      ],
    },

    martinique: {
      title: "Site internet pour un hébergement touristique en Martinique",
      desc: "Villa, gîte vue mer ou chambre d'hôtes en Martinique : un site de réservation directe pour capter la clientèle métropole et croisière, sans commissions. GroupSolution, dès 250€.",
      keywords: "site internet gîte Martinique, location saisonnière 972, réservation directe Martinique, villa vue mer Les Salines, chambre d'hôtes Fort-de-France, éviter commissions Airbnb Martinique",
      tag: "Tourisme & hébergement · Martinique",
      h1: "Hébergement touristique en Martinique : votre site de réservation directe",
      lead: "Villas du sud balnéaire, gîtes vue mer, chambres d'hôtes du nord verdoyant : la Martinique attire une clientèle métropolitaine importante, surtout l'hiver. Chaque réservation via une plateforme vous coûte une commission qu'un site à vous permet de récupérer.",
      sections: [
        { h2: "Le vrai coût des plateformes",
          html: "<p>Airbnb, Booking et consorts apportent de la visibilité mais prélèvent 15 à 25 % et gardent la relation client. Sur une saison d'hiver bien remplie, la facture est lourde. Un site de réservation directe vous rend les clients fidèles et les recommandations — sans commission.</p>" },
        { h2: "Ce qu'attend le voyageur en Martinique",
          html: "<ul><li><strong>Des photos qui vendent le rêve</strong> : vue mer, piscine, plage des Salines à proximité.</li><li><strong>Les infos pratiques</strong> : capacité, équipements, distance des plages et sites.</li><li><strong>La confiance</strong> : avis, présentation, réactivité.</li><li><strong>Une demande de réservation</strong> simple, en français comme en anglais.</li></ul>" },
        { h2: "Capter les recherches directes",
          html: "<p>« Villa vue mer Martinique », « gîte sud Martinique », « où dormir Sainte-Anne » : un site optimisé sur ces requêtes vous place hors des plateformes, face au voyageur qui préfère réserver en direct.</p>" },
        { h2: "Notre approche pour l'hébergement martiniquais",
          html: "<p>On crée un site vitrine élégant qui valorise votre bien : galerie, descriptif, atouts du secteur, formulaire de demande. Dès 250€, pour transformer la vitrine en canal de réservation directe.</p>" },
      ],
      callout: "La clientèle métropolitaine réserve son séjour d'hiver dès l'automne. Être visible et crédible en ligne à ce moment-là — avec un vrai site, pas seulement une annonce — fait la différence entre une saison pleine et une saison à trous.",
      faq: [
        { q: "Un site va-t-il remplacer Airbnb et Booking ?", a: "Pas immédiatement, et ce n'est pas l'objectif : les plateformes servent la découverte. Votre site capte les réservations directes et récupère les commissions sur cette part-là." },
        { q: "Combien coûte un site pour ma location en Martinique ?", a: "Un site vitrine avec galerie et formulaire démarre à 250€ ; moteur de réservation avec calendrier et paiement sur devis." },
        { q: "Je loue un seul bien, est-ce rentable ?", a: "Oui : quelques réservations directes récupérées sur les commissions amortissent le site, qui devient un actif à vous." },
        { q: "Pouvez-vous faire un site bilingue ?", a: "Oui, recommandé pour ne pas perdre la clientèle anglophone et de croisière." },
      ],
    },

    'nouvelle-caledonie': {
      title: "Site internet pour un hébergement touristique en Nouvelle-Calédonie",
      desc: "Gîte, hôtel, accueil en tribu ou location en Nouvelle-Calédonie : un site bilingue pour capter la clientèle métropole, australienne et néo-zélandaise en direct. GroupSolution, dès 250€.",
      keywords: "site internet hébergement Nouvelle-Calédonie, gîte Île des Pins, réservation directe 988, accueil en tribu Calédonie, location Nouméa, tourisme lagon Nouvelle-Calédonie",
      tag: "Tourisme & hébergement · Nouvelle-Calédonie",
      h1: "Hébergement touristique en Nouvelle-Calédonie : capter le marché du Pacifique en direct",
      lead: "Lagon classé à l'UNESCO, Île des Pins, îlots et accueil en tribu : la Nouvelle-Calédonie séduit une clientèle métropolitaine, mais aussi australienne et néo-zélandaise toute proche. Cette clientèle réserve en ligne, souvent en anglais.",
      sections: [
        { h2: "Un marché régional à portée de site",
          html: "<p>L'Australie et la Nouvelle-Zélande sont à quelques heures de vol : ces voyageurs, anglophones, préparent et réservent leur séjour sur Internet. Un hébergement visible et compréhensible en anglais capte un marché que beaucoup d'établissements locaux laissent aux grandes plateformes.</p>" },
        { h2: "Ce qui déclenche la réservation",
          html: "<ul><li><strong>Des photos</strong> du lagon, de l'îlot, du logement.</li><li><strong>Les atouts</strong> : plongée, snorkeling, accès îlots, expérience d'accueil en tribu.</li><li><strong>Infos pratiques et confiance</strong> : capacité, transferts, avis.</li><li><strong>Une réservation directe</strong>, idéalement bilingue.</li></ul>" },
        { h2: "Se positionner hors des plateformes",
          html: "<p>« Gîte Île des Pins », « hébergement lagon Nouvelle-Calédonie », « where to stay New Caledonia » : un site optimisé et bilingue capte ces recherches et la réservation en direct, sans commission.</p>" },
        { h2: "Notre approche pour l'hébergement calédonien",
          html: "<p>On crée un site vitrine soigné, bilingue si besoin, qui valorise votre bien et l'expérience du lagon, avec galerie et formulaire de demande. Dès 250€.</p>" },
      ],
      callout: "La clientèle australienne et néo-zélandaise, toute proche, réserve en ligne et en anglais. Un hébergement doté d'un vrai site bilingue capte ce marché régional que beaucoup négligent encore.",
      faq: [
        { q: "Pourquoi un site si je suis déjà sur les plateformes ?", a: "Les plateformes prélèvent une commission et gardent vos clients. Un site à vous, bilingue, capte la réservation directe — fidèles, recommandations, marché australien/néo-zélandais — sans commission." },
        { q: "Combien coûte un site pour mon hébergement en Nouvelle-Calédonie ?", a: "Un site vitrine avec galerie et formulaire démarre à 250€ ; version bilingue et calendrier sur devis clair." },
        { q: "Le bilingue français/anglais est-il vraiment utile ici ?", a: "Oui : une part importante de la clientèle vient d'Australie et de Nouvelle-Zélande. Une version anglaise est un vrai levier de réservations." },
        { q: "Je débute la location, est-ce adapté ?", a: "Oui, on construit un site simple à gérer et on vous forme pour l'entretenir vous-même." },
      ],
    },

    'polynesie-francaise': {
      title: "Site internet pour une pension ou un hébergement en Polynésie française",
      desc: "Pension de famille, hôtel ou location en Polynésie : un site bilingue de réservation directe pour capter une clientèle internationale, sans commissions d'OTA. GroupSolution, dès 250€.",
      keywords: "site internet pension Polynésie, hébergement Bora-Bora Moorea, réservation directe Tahiti, pension de famille Polynésie, éviter commissions Booking Polynésie, tourisme Polynésie française",
      tag: "Tourisme & hébergement · Polynésie française",
      h1: "Hébergement en Polynésie : la réservation directe, clé de survie des pensions",
      lead: "Face aux grands hôtels et aux plateformes mondiales, la pension de famille polynésienne joue une carte décisive : la réservation directe. Sur Tahiti, Moorea ou Bora-Bora, une clientèle internationale de rêve prépare tout en ligne, en anglais.",
      sections: [
        { h2: "Le tourisme est le cœur de l'économie — et il est en ligne",
          html: "<p>En Polynésie, le voyageur international réserve son hébergement des mois à l'avance, sur Internet et en anglais. Les OTA (Booking, Expedia…) et les grands hôtels captent l'attention et prélèvent de lourdes commissions. Pour une pension, un site bilingue est le meilleur moyen de reprendre la main.</p>" },
        { h2: "Ce qui fait choisir votre pension",
          html: "<ul><li><strong>Des photos superbes</strong> : le motu, le lagon, la vue, les fare.</li><li><strong>Une présentation bilingue</strong> claire et chaleureuse.</li><li><strong>La confiance</strong> : avis, accueil, transferts, activités.</li><li><strong>Une réservation directe</strong> simple, sans commission d'intermédiaire.</li></ul>" },
        { h2: "Capter la recherche internationale",
          html: "<p>« Pension Bora-Bora », « guesthouse Moorea », « where to stay Tahiti » : un site optimisé et bilingue vous rend visible face à cette demande mondiale et transforme le voyageur en réservation directe.</p>" },
        { h2: "Notre approche pour l'hébergement polynésien",
          html: "<p>On crée un site vitrine élégant et bilingue qui valorise votre pension et l'expérience polynésienne, avec galerie et formulaire de réservation. Dès 250€, pour réduire votre dépendance aux OTA saison après saison.</p>" },
      ],
      callout: "Face aux grands hôtels et aux plateformes, la pension de famille qui possède un vrai site bilingue capte la réservation directe — et fidélise une clientèle internationale de rêve, sans reverser 15 à 25 % de commission.",
      faq: [
        { q: "Les OTA m'apportent des clients, pourquoi un site en plus ?", a: "Elles apportent de la visibilité mais prélèvent de lourdes commissions et gardent la relation. Un site bilingue capte la réservation directe — clients fidèles, recommandations, voyageurs qui préfèrent traiter avec vous — et récupère ces commissions." },
        { q: "Combien coûte un site pour ma pension en Polynésie ?", a: "Un site vitrine bilingue avec galerie et formulaire de réservation démarre à 250€ ; moteur de réservation avec calendrier et paiement sur devis clair." },
        { q: "Le bilingue est-il indispensable ?", a: "Oui, ici plus qu'ailleurs : la majorité de votre clientèle est internationale et anglophone. Une version anglaise est essentielle." },
        { q: "Je gère une petite pension, est-ce rentable ?", a: "Oui : même quelques réservations directes par mois récupérées sur les commissions amortissent largement le site, qui devient un actif à vous." },
      ],
    },
  },

  /* ═════════════════ BÂTIMENT & ARTISANS ═════════════════ */
  'batiment-artisans': {
    guadeloupe: {
      title: "Site internet pour un artisan du bâtiment en Guadeloupe",
      desc: "Maçon, couvreur, électricien, plombier ou entreprise de rénovation en Guadeloupe : un site + Google pour recevoir des demandes de devis. Guide GroupSolution, site vitrine dès 250€.",
      keywords: "site internet artisan Guadeloupe, BTP 971, devis en ligne bâtiment Guadeloupe, référencement plombier Baie-Mahault, entreprise rénovation Pointe-à-Pitre, site maçon couvreur Antilles",
      tag: "Bâtiment & artisans · Guadeloupe",
      h1: "Artisans et bâtiment en Guadeloupe : un site qui génère des demandes de devis",
      lead: "Le BTP guadeloupéen ne manque pas de travail — construction, rénovation, mise aux normes parasismiques et paracycloniques. Mais beaucoup d'artisans restent invisibles en ligne, alors que leurs futurs clients, eux, cherchent sur Google.",
      sections: [
        { h2: "Vos clients cherchent un artisan en ligne, pas dans l'annuaire",
          html: "<p>Quand un particulier de Baie-Mahault a une fuite, ou qu'un propriétaire prépare une rénovation à Pointe-à-Pitre, il tape « plombier près de moi », « couvreur Guadeloupe » ou « entreprise rénovation 971 ». S'il ne tombe que sur vos concurrents, vous ne serez même pas dans la short-list. Un site simple, clair, avec vos réalisations et un bouton devis, vous remet dans la course.</p>" },
        { h2: "Ce qui inspire confiance dans le bâtiment",
          html: "<ul><li><strong>Vos chantiers en photos</strong> (avant/après) : rien ne rassure plus qu'un travail visible.</li><li><strong>Vos spécialités</strong> clairement listées : gros œuvre, toiture, électricité, rénovation, respect des normes parasismiques.</li><li><strong>Les avis clients</strong> et références locales.</li><li><strong>Un formulaire de devis</strong> et un numéro cliquable : capter la demande au moment où elle est chaude.</li></ul>" },
        { h2: "Le contexte antillais : normes et rénovation",
          html: "<p>Aux Antilles, la contrainte sismique et cyclonique est un vrai sujet : les clients cherchent des artisans qui maîtrisent les normes de construction et de mise en sécurité. Mettre en avant cette expertise sur votre site — sans surpromesse — vous distingue et attire des chantiers de rénovation et de mise aux normes, un marché porteur en Guadeloupe.</p>" },
        { h2: "Notre approche pour les artisans du BTP",
          html: "<p>On construit un site vitrine efficace : présentation de vos métiers, galerie de réalisations, zone d'intervention, avis et formulaire de devis relié à votre téléphone. Pas de site vitrine décoratif — un outil qui fait sonner le téléphone. Démarrage à 250€, avec le référencement local pour apparaître sur « votre métier + votre secteur ».</p>" },
      ],
      callout: "Un artisan qui apparaît sur Google avec des photos de chantiers et quelques bons avis capte des demandes de devis en continu — pendant que le concurrent sans site attend encore le bouche-à-oreille.",
      faq: [
        { q: "Je suis débordé, à quoi bon un site si je n'ai pas le temps ?", a: "Un site n'est pas fait pour vous submerger, mais pour choisir vos chantiers : quand les demandes arrivent en ligne, vous prenez les plus rentables et déclinez le reste. C'est un actif qui travaille pour vous même quand vous êtes sur un chantier." },
        { q: "Combien coûte un site pour mon entreprise de bâtiment en Guadeloupe ?", a: "Un site vitrine professionnel avec galerie de réalisations et formulaire de devis démarre à 250€. On adapte selon le nombre de métiers et de pages, avec un devis transparent." },
        { q: "Faut-il beaucoup de photos ?", a: "Quelques bonnes photos de chantiers terminés suffisent pour démarrer. On vous montre comment les prendre correctement avec un simple téléphone, et on enrichit la galerie au fil des chantiers." },
        { q: "Vais-je apparaître sur Google pour ma commune ?", a: "C'est l'objectif : on optimise le site et votre fiche Google pour les recherches « métier + commune » (plombier Baie-Mahault, couvreur Le Gosier…), là où vos clients vous cherchent vraiment." },
      ],
    },

    reunion: {
      title: "Site internet pour un artisan du bâtiment à La Réunion",
      desc: "Maçon, couvreur, électricien, plombier ou entreprise de rénovation à La Réunion : un site + Google pour recevoir des demandes de devis. GroupSolution, site vitrine dès 250€.",
      keywords: "site internet artisan Réunion, BTP 974, devis en ligne bâtiment Réunion, référencement plombier Saint-Denis, entreprise rénovation Saint-Pierre, site maçon couvreur Réunion",
      tag: "Bâtiment & artisans · La Réunion",
      h1: "Artisans et bâtiment à La Réunion : un site qui génère des demandes de devis",
      lead: "Construction en pente, rénovation, adaptation au climat tropical : le BTP réunionnais a ses contraintes propres. Beaucoup d'artisans restent pourtant invisibles en ligne, alors que leurs futurs clients, eux, cherchent sur Google.",
      sections: [
        { h2: "Vos clients cherchent un artisan en ligne",
          html: "<p>Quand un particulier de Saint-Denis a une fuite ou qu'un propriétaire de Saint-Pierre prépare une rénovation, il tape « plombier près de moi », « couvreur Réunion » ou « entreprise rénovation 974 ». S'il ne trouve que vos concurrents, vous n'êtes pas dans la short-list. Un site clair avec vos réalisations et un bouton devis vous y remet.</p>" },
        { h2: "Ce qui inspire confiance dans le bâtiment",
          html: "<ul><li><strong>Vos chantiers en photos</strong> (avant/après).</li><li><strong>Vos spécialités</strong> : gros œuvre, toiture, électricité, rénovation.</li><li><strong>Les avis clients</strong> et références locales.</li><li><strong>Un formulaire de devis</strong> et un numéro cliquable.</li></ul>" },
        { h2: "Le contexte réunionnais : relief et climat",
          html: "<p>Terrains en pente, fortes pluies, cyclones, humidité : les clients réunionnais cherchent des artisans qui maîtrisent ces contraintes. Mettre en avant ce savoir-faire sur votre site — sans surpromesse — vous distingue et attire les chantiers de construction et de rénovation adaptés.</p>" },
        { h2: "Notre approche pour les artisans réunionnais",
          html: "<p>On construit un site vitrine efficace : métiers, galerie de réalisations, zone d'intervention, avis, formulaire de devis relié à votre téléphone. Un outil qui fait sonner le téléphone. Dès 250€, avec le référencement local « métier + secteur ».</p>" },
      ],
      callout: "Relief et climat réunionnais (pluies, cyclones, terrains pentus) imposent un vrai savoir-faire. Le montrer en ligne, photos de chantiers à l'appui, rassure le client et fait signer le devis.",
      faq: [
        { q: "Je suis débordé, à quoi bon un site ?", a: "Un site vous aide à choisir vos chantiers : quand les demandes arrivent en ligne, vous prenez les plus rentables et déclinez le reste. C'est un actif qui travaille même quand vous êtes sur un chantier." },
        { q: "Combien coûte un site pour mon entreprise du bâtiment à La Réunion ?", a: "Un site vitrine avec galerie de réalisations et formulaire de devis démarre à 250€, avec un devis transparent selon le nombre de métiers et de pages." },
        { q: "Faut-il beaucoup de photos ?", a: "Quelques bonnes photos de chantiers terminés suffisent pour démarrer ; on vous montre comment les prendre au téléphone et on enrichit au fil du temps." },
        { q: "Vais-je apparaître sur Google pour ma commune ?", a: "C'est l'objectif : on optimise site et fiche Google pour « métier + commune » (plombier Saint-Denis, couvreur Saint-Pierre…)." },
      ],
    },

    mayotte: {
      title: "Site internet pour un artisan du bâtiment à Mayotte",
      desc: "Maçon, couvreur, électricien ou entreprise de rénovation à Mayotte : un site + Google pour capter des chantiers dans un secteur en forte tension. GroupSolution, dès 250€.",
      keywords: "site internet artisan Mayotte, BTP 976, devis en ligne bâtiment Mayotte, référencement maçon Mamoudzou, entreprise construction Mayotte, rénovation Petite-Terre",
      tag: "Bâtiment & artisans · Mayotte",
      h1: "Bâtiment et artisans à Mayotte : se démarquer dans un secteur en tension",
      lead: "Mayotte connaît un besoin massif de construction et de rénovation : logements, écoles, infrastructures, mise aux normes. Le travail ne manque pas — mais l'artisan visible en ligne, avec ses chantiers et ses avis, capte les meilleurs contrats.",
      sections: [
        { h2: "Un marché du bâtiment sous forte demande",
          html: "<p>Avec la croissance démographique la plus rapide de France et un rattrapage d'équipements considérable, le BTP mahorais est très sollicité. Dans ce contexte, se rendre visible en ligne permet de choisir ses chantiers et de se positionner face à une concurrence encore peu digitalisée.</p>" },
        { h2: "Ce qui inspire confiance",
          html: "<ul><li><strong>Vos chantiers en photos</strong> (avant/après).</li><li><strong>Vos spécialités</strong> : construction, toiture, électricité, rénovation.</li><li><strong>Les avis</strong>, encore rares ici : un vrai facteur de différenciation.</li><li><strong>Un formulaire de devis</strong> et un numéro cliquable.</li></ul>" },
        { h2: "Le contexte mahorais : normes et sécurité",
          html: "<p>Mayotte est concernée par le risque sismique (l'essaim sismique lié au volcan sous-marin l'a rappelé) : les clients cherchent des artisans sérieux, respectueux des règles de construction. Mettre en avant ce sérieux, sans surpromesse, vous distingue durablement.</p>" },
        { h2: "Notre approche pour les artisans mahorais",
          html: "<p>On construit un site vitrine efficace et léger : métiers, réalisations, zone d'intervention, formulaire de devis. Un outil concret pour capter la demande. Dès 250€, avec le référencement local.</p>" },
      ],
      callout: "Mayotte a un besoin colossal de construction et de rénovation. Un artisan visible en ligne, avec ses chantiers et ses avis, se distingue nettement dans un marché sous tension où beaucoup n'ont aucune présence web.",
      faq: [
        { q: "J'ai déjà trop de travail, pourquoi un site ?", a: "Justement pour choisir : quand les demandes arrivent en ligne, vous gardez les chantiers les plus rentables. Le site travaille pour vous en continu, sans effort quotidien." },
        { q: "Combien coûte un site pour mon entreprise du bâtiment à Mayotte ?", a: "Un site vitrine avec galerie et formulaire de devis démarre à 250€, avec un devis clair selon vos besoins." },
        { q: "La connexion est parfois limitée, est-ce gênant ?", a: "Non : on conçoit des sites légers qui chargent vite même en réseau faible." },
        { q: "Vais-je apparaître sur Google pour Mamoudzou ?", a: "Oui : on optimise site et fiche Google pour « métier + commune » (maçon Mamoudzou, couvreur Mayotte…)." },
      ],
    },

    guyane: {
      title: "Site internet pour une entreprise de BTP ou de logistique en Guyane",
      desc: "BTP, construction, terrassement ou logistique en Guyane : un site + Google pour capter chantiers et contrats dans un territoire en pleine croissance. GroupSolution, dès 250€.",
      keywords: "site internet BTP Guyane, entreprise bâtiment 973, logistique Guyane, devis en ligne construction Cayenne, terrassement Kourou, référencement artisan Guyane",
      tag: "Bâtiment & artisans · Guyane",
      h1: "BTP et logistique en Guyane : un site pour capter chantiers et contrats",
      lead: "Entre le Centre spatial de Kourou, la plus forte croissance démographique de France et la logistique d'un territoire enclavé, le BTP guyanais ne connaît pas la crise. Encore faut-il être visible en ligne pour capter les chantiers et les contrats.",
      sections: [
        { h2: "Un secteur porteur… mais une visibilité à construire",
          html: "<p>Construction de logements, chantiers publics, soutien au spatial, terrassement en milieu tropical : la demande est forte à Cayenne, Kourou, Matoury ou Saint-Laurent. Les donneurs d'ordre et particuliers cherchent pourtant leurs prestataires en ligne. Sans site, vous dépendez du seul bouche-à-oreille.</p>" },
        { h2: "Ce qui rassure donneurs d'ordre et particuliers",
          html: "<ul><li><strong>Vos réalisations en photos</strong> et vos références.</li><li><strong>Vos domaines</strong> : gros œuvre, VRD, terrassement, logistique, rénovation.</li><li><strong>Vos moyens</strong> : équipe, matériel, zone d'intervention.</li><li><strong>Un formulaire de devis</strong> clair et un contact direct.</li></ul>" },
        { h2: "Le contexte guyanais : croissance et logistique",
          html: "<p>Tout, ou presque, arrive par bateau ou par avion : la logistique est un enjeu majeur, et les acteurs fiables sont recherchés. Un site qui affiche votre sérieux, vos moyens et votre zone d'intervention vous positionne auprès des entreprises comme des collectivités.</p>" },
        { h2: "Notre approche pour le BTP et la logistique en Guyane",
          html: "<p>On construit un site vitrine crédible et professionnel : réalisations, domaines d'expertise, moyens, formulaire de devis. Dès 250€, avec le référencement local sur vos métiers et vos communes.</p>" },
      ],
      callout: "Entre le spatial de Kourou, la croissance démographique et la logistique d'un territoire enclavé, le BTP guyanais reste porteur — mais c'est en ligne que se décident aujourd'hui de plus en plus de chantiers et de contrats.",
      faq: [
        { q: "Le carnet de commandes est plein, pourquoi un site ?", a: "Pour sécuriser l'avenir et choisir vos chantiers : un site vous amène des demandes qualifiées en continu, et vous prenez les plus rentables. C'est aussi un gage de crédibilité face aux donneurs d'ordre." },
        { q: "Combien coûte un site pour mon entreprise de BTP en Guyane ?", a: "Un site vitrine professionnel avec réalisations et formulaire de devis démarre à 250€, avec un devis transparent selon vos besoins." },
        { q: "Je travaille surtout pour des professionnels, est-ce adapté ?", a: "Oui : un site sérieux qui présente vos moyens et vos références rassure les entreprises et les collectivités autant que les particuliers." },
        { q: "Vais-je apparaître sur Google pour ma commune ?", a: "Oui : on optimise pour « métier + commune » (terrassement Kourou, BTP Cayenne…), là où vos clients vous cherchent." },
      ],
    },

    martinique: {
      title: "Site internet pour un artisan du bâtiment en Martinique",
      desc: "Maçon, couvreur, électricien, plombier ou entreprise de rénovation en Martinique : un site + Google pour recevoir des demandes de devis. GroupSolution, site vitrine dès 250€.",
      keywords: "site internet artisan Martinique, BTP 972, devis en ligne bâtiment Martinique, référencement plombier Fort-de-France, entreprise rénovation Le Lamentin, site maçon couvreur Antilles",
      tag: "Bâtiment & artisans · Martinique",
      h1: "Artisans et bâtiment en Martinique : un site qui génère des demandes de devis",
      lead: "Rénovation d'un parc immobilier vieillissant, mise aux normes parasismiques, construction : le BTP martiniquais ne manque pas de travail. Mais beaucoup d'artisans restent invisibles en ligne, quand leurs clients, eux, cherchent sur Google.",
      sections: [
        { h2: "Vos clients cherchent un artisan en ligne",
          html: "<p>Un particulier du Lamentin avec une fuite, un propriétaire de Fort-de-France qui rénove : ils tapent « plombier près de moi », « couvreur Martinique », « entreprise rénovation 972 ». Sans site avec vos réalisations et un bouton devis, vous n'êtes pas dans la course.</p>" },
        { h2: "Ce qui inspire confiance dans le bâtiment",
          html: "<ul><li><strong>Vos chantiers en photos</strong> (avant/après).</li><li><strong>Vos spécialités</strong> : gros œuvre, toiture, électricité, rénovation, mise aux normes.</li><li><strong>Les avis clients</strong> et références locales.</li><li><strong>Un formulaire de devis</strong> et un numéro cliquable.</li></ul>" },
        { h2: "Le contexte antillais : normes parasismiques",
          html: "<p>Comme toutes les Antilles, la Martinique est en zone sismique forte : les clients cherchent des artisans qui maîtrisent les normes parasismiques et la mise en sécurité. Afficher cette expertise sur votre site vous distingue et attire les chantiers de rénovation et de mise aux normes.</p>" },
        { h2: "Notre approche pour les artisans martiniquais",
          html: "<p>On construit un site vitrine efficace : métiers, galerie de réalisations, zone d'intervention, avis, formulaire de devis relié à votre téléphone. Dès 250€, avec le référencement local « métier + secteur ».</p>" },
      ],
      callout: "Comme aux Antilles voisines, la Martinique impose des normes parasismiques strictes. L'artisan qui affiche cette maîtrise en ligne inspire confiance immédiatement — et capte les chantiers de rénovation et de mise aux normes.",
      faq: [
        { q: "Je suis débordé, à quoi bon un site ?", a: "Un site vous aide à choisir vos chantiers : les demandes arrivent en ligne, vous gardez les plus rentables. C'est un actif qui travaille pour vous en continu." },
        { q: "Combien coûte un site pour mon entreprise de bâtiment en Martinique ?", a: "Un site vitrine avec galerie de réalisations et formulaire de devis démarre à 250€, avec un devis transparent." },
        { q: "Faut-il beaucoup de photos ?", a: "Quelques bonnes photos de chantiers terminés suffisent ; on vous montre comment les prendre et on enrichit au fil des chantiers." },
        { q: "Vais-je apparaître sur Google pour ma commune ?", a: "Oui : on optimise pour « métier + commune » (plombier Fort-de-France, couvreur Le Lamentin…)." },
      ],
    },

    'nouvelle-caledonie': {
      title: "Site internet pour une entreprise de BTP ou de logistique en Nouvelle-Calédonie",
      desc: "BTP, construction, rénovation ou logistique en Nouvelle-Calédonie : un site + Google pour capter chantiers et contrats autour de Nouméa et du nickel. GroupSolution, dès 250€.",
      keywords: "site internet BTP Nouvelle-Calédonie, entreprise bâtiment Nouméa, logistique 988, devis en ligne construction Dumbéa, terrassement Mont-Dore, référencement artisan Calédonie",
      tag: "Bâtiment & artisans · Nouvelle-Calédonie",
      h1: "BTP et logistique en Nouvelle-Calédonie : un site pour capter chantiers et contrats",
      lead: "Autour du nickel — usines, mines, infrastructures — et de l'expansion du Grand Nouméa, le BTP calédonien reste porteur. Une présence en ligne solide permet de capter aussi bien les particuliers que les marchés professionnels.",
      sections: [
        { h2: "Un secteur soutenu par le nickel et l'urbanisation",
          html: "<p>Entre l'activité minière et industrielle du nickel et la croissance de Dumbéa, du Mont-Dore et de Koné, la demande de construction, de rénovation et de logistique est réelle. Particuliers et entreprises cherchent leurs prestataires en ligne : un site vous place dans la sélection.</p>" },
        { h2: "Ce qui rassure clients et donneurs d'ordre",
          html: "<ul><li><strong>Vos réalisations en photos</strong> et vos références.</li><li><strong>Vos domaines</strong> : gros œuvre, VRD, terrassement, logistique, rénovation.</li><li><strong>Vos moyens</strong> : équipe, matériel, zone d'intervention.</li><li><strong>Un formulaire de devis</strong> et un contact direct.</li></ul>" },
        { h2: "Le contexte calédonien : industrie et logistique",
          html: "<p>Le tissu industriel du nickel et l'insularité font de la logistique et de la fiabilité des enjeux majeurs. Un site qui affiche vos moyens, votre sérieux et votre zone d'intervention vous positionne auprès des entreprises comme des particuliers du Grand Nouméa.</p>" },
        { h2: "Notre approche pour le BTP et la logistique en Nouvelle-Calédonie",
          html: "<p>On construit un site vitrine crédible : réalisations, domaines d'expertise, moyens, formulaire de devis. Dès 250€, avec le référencement local sur vos métiers et vos communes.</p>" },
      ],
      callout: "Autour du nickel et de l'expansion du Grand Nouméa (Dumbéa, Mont-Dore, Koné), le BTP calédonien reste porteur. Une présence en ligne solide capte particuliers comme professionnels — là où vos concurrents sans site restent invisibles.",
      faq: [
        { q: "Le carnet est plein, pourquoi un site ?", a: "Pour choisir vos chantiers et sécuriser l'avenir : un site amène des demandes qualifiées en continu et renforce votre crédibilité face aux donneurs d'ordre." },
        { q: "Combien coûte un site pour mon entreprise de BTP en Nouvelle-Calédonie ?", a: "Un site vitrine professionnel avec réalisations et formulaire de devis démarre à 250€, devis transparent selon vos besoins." },
        { q: "Je travaille surtout pour des professionnels, est-ce adapté ?", a: "Oui : un site qui présente vos moyens et vos références rassure entreprises et collectivités autant que les particuliers." },
        { q: "Vais-je apparaître sur Google pour ma commune ?", a: "Oui : on optimise pour « métier + commune » (BTP Nouméa, terrassement Dumbéa…)." },
      ],
    },

    'polynesie-francaise': {
      title: "Site internet pour un artisan du bâtiment en Polynésie française",
      desc: "Maçon, charpentier, électricien ou entreprise de rénovation en Polynésie : un site + Google pour capter des chantiers au-delà de votre île. GroupSolution, site vitrine dès 250€.",
      keywords: "site internet artisan Polynésie, BTP Tahiti, devis en ligne bâtiment Polynésie, construction fare, rénovation Papeete, référencement artisan Bora-Bora",
      tag: "Bâtiment & artisans · Polynésie française",
      h1: "Bâtiment et artisans en Polynésie : un site qui élargit votre zone de chalandise",
      lead: "Construction de fare et de pensions, rénovation, chantiers hôteliers : le bâtiment polynésien est actif, mais dispersé sur des archipels où les matériaux arrivent par bateau. Un artisan fiable et visible en ligne est recherché bien au-delà de son île.",
      sections: [
        { h2: "L'insularité change les règles du jeu",
          html: "<p>Entre Tahiti, Moorea, Bora-Bora et les archipels éloignés, trouver un artisan fiable n'est pas évident : le bouche-à-oreille ne franchit pas toujours le lagon. Un client de Papeete ou d'un motu cherche alors en ligne — et confie parfois son chantier à un professionnel d'une autre île. Un site vous rend accessible à cette demande.</p>" },
        { h2: "Ce qui inspire confiance",
          html: "<ul><li><strong>Vos chantiers en photos</strong> (fare, rénovation, hôtellerie).</li><li><strong>Vos spécialités</strong> : construction, charpente, électricité, rénovation.</li><li><strong>Votre zone d'intervention</strong> : les îles que vous couvrez.</li><li><strong>Un formulaire de devis</strong> et un contact direct.</li></ul>" },
        { h2: "Le contexte polynésien : logistique et normes",
          html: "<p>Acheminement des matériaux par bateau, contraintes climatiques (cyclones), habitat traditionnel : le client cherche un artisan qui maîtrise ces réalités. L'afficher sur votre site, réalisations à l'appui, vous distingue et étend votre rayon d'action.</p>" },
        { h2: "Notre approche pour les artisans polynésiens",
          html: "<p>On construit un site vitrine efficace : métiers, galerie de réalisations, îles couvertes, formulaire de devis. Dès 250€, avec le référencement local pour être trouvé au-delà de votre île.</p>" },
      ],
      callout: "Sur des archipels où les matériaux arrivent par bateau, un artisan fiable et visible en ligne est recherché bien au-delà de son île. Le site élargit concrètement votre zone de chalandise à toute la Polynésie.",
      faq: [
        { q: "Je travaille surtout sur mon île, un site sert-il ?", a: "Oui : il vous rend visible auprès des clients des autres îles qui peinent à trouver un artisan fiable. Beaucoup de chantiers se décident en ligne, à distance." },
        { q: "Combien coûte un site pour mon entreprise du bâtiment en Polynésie ?", a: "Un site vitrine avec galerie de réalisations et formulaire de devis démarre à 250€, avec un devis transparent." },
        { q: "Faut-il beaucoup de photos ?", a: "Quelques bonnes photos de chantiers terminés suffisent ; on vous montre comment les prendre et on enrichit au fil du temps." },
        { q: "Vais-je apparaître sur Google pour ma zone ?", a: "Oui : on optimise pour « métier + île/commune » (rénovation Papeete, artisan Bora-Bora…), là où vos clients vous cherchent." },
      ],
    },
  },

};
